version: '2'
services:
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
